### ISSUE TITLE
How do I parse the LatLng stream?

### ISSUE THREAD

**Issue by MrBean2016** [inexcitus/stravadotnet#33]
First, thank you for this excellent library. 
I have managed to read the times-stream and I have done some calculations that I want present the coordinates for.

How do I parse the LatLng stream?
I.e. I want to convert it to a list of Coordinates

 var LatLng = await client.Streams.GetActivityStreamAsync("xxxxxx", StreamType.LatLng);
  List<Coordinate> test = .....

I cannot figure out any conversion here except parsing .ToString for each element. there must be a better way.

Could someone assist me here?
Thanks,

**Comment by inexcitus** [comment]
Hello,

because the Stream is generic (data is List<object>) I don't see any other possible way than to parse the data, sorry.

In my iOS library, I went for a slightly different approach:

- There is a class "ActivityStreams" that holds an instance of a LatLng, an Altitude- and a DistanceStream object. The data is parsed automatically when receiving the streams.

You could implement something like that.

**Comment by MrBean2016** [comment]
Hi,
Ok, no problem.
I made a simple "converter" for this

                var LatLng = await client.Streams.GetActivityStreamAsync("xxx", StreamType.LatLng);

                List<Coordinate> latlng = new List<Coordinate>();
                foreach (var v in LatLng[0].Data)
                {
                    var q = v.ToString();
                    q = q.Trim(new Char[] { '[', ']', '\r', '\n' });                    
                    var lat = double.Parse(q.Split(',')[0], System.Globalization.CultureInfo.InvariantCulture);
                    var lng = double.Parse(q.Split(',')[1], System.Globalization.CultureInfo.InvariantCulture);
                    latlng.Add(new Coordinate(lat, lng));                    
                }
